/* ========================================
   HYPE-MAN STUDIO - JavaScript Engine
   Comic Photo Booth with Social Sharing
======================================== */

// ========================================
// DOM ELEMENTS
// ========================================
const webcam = document.getElementById('webcam');
const filterCanvas = document.getElementById('filter-canvas');
const captureCanvas = document.getElementById('capture-canvas');
const hypeContainer = document.getElementById('hype-words-container');
const hypeInput = document.getElementById('hype-input');
const spawnBtn = document.getElementById('spawn-btn');
const captureBtn = document.getElementById('capture-btn');
const whatsappBridge = document.getElementById('whatsapp-bridge');
const sharePopup = document.getElementById('share-popup');
const closePopupBtn = document.getElementById('close-popup');
const previewImage = document.getElementById('preview-image');
const shareWhatsappBtn = document.getElementById('share-whatsapp');
const shareInstagramBtn = document.getElementById('share-instagram');
const instagramHint = document.getElementById('instagram-hint');
const cameraContainer = document.getElementById('camera-container');
const welcomePopup = document.getElementById('welcome-popup');
const welcomeStartBtn = document.getElementById('welcome-start');
const clearAllBtn = document.getElementById('clear-all-btn');

// ========================================
// STATE
// ========================================
let currentImageBlob = null;
let stream = null;
const websiteUrl = 'https://hypeman-studio.app'; // Replace with your actual URL

// Comic word variations for random spawning
const comicEffects = ['POW!', 'BOOM!', 'ZAP!', 'WHAM!', 'BAM!', 'KAPOW!'];
const wordStyles = ['pow', 'boom', 'zap', 'bubble'];

// ========================================
// WELCOME POPUP SYSTEM
// ========================================
function checkFirstVisit() {
    const hasVisited = localStorage.getItem('hypeman-visited');
    if (!hasVisited) {
        showWelcomePopup();
    }
}

function showWelcomePopup() {
    welcomePopup.classList.remove('hidden');
}

function hideWelcomePopup() {
    welcomePopup.classList.add('hidden');
    localStorage.setItem('hypeman-visited', 'true');
}

// ========================================
// CAMERA INITIALIZATION
// ========================================
async function initCamera() {
    try {
        stream = await navigator.mediaDevices.getUserMedia({
            video: {
                facingMode: 'user',
                width: { ideal: 1280 },
                height: { ideal: 720 }
            },
            audio: false
        });

        webcam.srcObject = stream;
        await webcam.play();

        // Set canvas dimensions
        filterCanvas.width = webcam.videoWidth;
        filterCanvas.height = webcam.videoHeight;

        console.log('📸 Camera initialized successfully!');

    } catch (error) {
        console.error('Camera error:', error);
        showCameraError();
    }
}

function showCameraError() {
    cameraContainer.innerHTML = `
        <div class="camera-error">
            <h2>📷 Camera Access Needed</h2>
            <p>Please allow camera access to use Hype-Man Studio.<br>
            Check your browser settings and refresh the page.</p>
        </div>
    `;
}

// ========================================
// HYPE WORDS SYSTEM (PERSISTENT)
// ========================================
function spawnHypeWord(text, isAutoGenerated = false) {
    const word = document.createElement('div');
    word.className = 'hype-word';
    if (isAutoGenerated) {
        word.classList.add('auto-generated');
    }

    // Add random style
    const randomStyle = wordStyles[Math.floor(Math.random() * wordStyles.length)];
    word.classList.add(randomStyle);

    // Random position (avoiding edges)
    const x = 10 + Math.random() * 70; // 10-80% from left
    const y = 10 + Math.random() * 60; // 10-70% from top

    // Random rotation
    const rotation = -20 + Math.random() * 40; // -20 to +20 degrees

    word.style.left = `${x}%`;
    word.style.top = `${y}%`;
    word.style.setProperty('--rotation', `${rotation}deg`);

    // Create text span
    const textSpan = document.createElement('span');
    textSpan.className = 'hype-text';
    textSpan.textContent = text;
    word.appendChild(textSpan);

    // Create remove button
    const removeBtn = document.createElement('button');
    removeBtn.className = 'remove-word-btn';
    removeBtn.innerHTML = '×';
    removeBtn.title = 'Remove this word';
    removeBtn.addEventListener('click', (e) => {
        e.stopPropagation();
        word.classList.add('removing');
        setTimeout(() => word.remove(), 300);
    });
    word.appendChild(removeBtn);

    // Add starburst for special effects
    if (Math.random() > 0.5 && !word.classList.contains('bubble')) {
        const starburst = document.createElement('div');
        starburst.className = 'starburst';
        word.insertBefore(starburst, textSpan);
    }

    // Make word draggable
    makeDraggable(word);

    hypeContainer.appendChild(word);

    // Words stay on screen permanently until removed or capture
    // No auto-remove timeout
}

function makeDraggable(element) {
    let isDragging = false;
    let startX, startY, initialLeft, initialTop;

    element.addEventListener('mousedown', startDrag);
    element.addEventListener('touchstart', startDrag, { passive: false });

    function startDrag(e) {
        if (e.target.classList.contains('remove-word-btn')) return;

        isDragging = true;
        element.classList.add('dragging');

        const touch = e.touches ? e.touches[0] : e;
        startX = touch.clientX;
        startY = touch.clientY;

        const rect = element.getBoundingClientRect();
        const parentRect = hypeContainer.getBoundingClientRect();
        initialLeft = rect.left - parentRect.left;
        initialTop = rect.top - parentRect.top;

        document.addEventListener('mousemove', drag);
        document.addEventListener('touchmove', drag, { passive: false });
        document.addEventListener('mouseup', stopDrag);
        document.addEventListener('touchend', stopDrag);

        e.preventDefault();
    }

    function drag(e) {
        if (!isDragging) return;

        const touch = e.touches ? e.touches[0] : e;
        const dx = touch.clientX - startX;
        const dy = touch.clientY - startY;

        const parentRect = hypeContainer.getBoundingClientRect();
        const newLeft = ((initialLeft + dx) / parentRect.width) * 100;
        const newTop = ((initialTop + dy) / parentRect.height) * 100;

        element.style.left = `${Math.max(0, Math.min(90, newLeft))}%`;
        element.style.top = `${Math.max(0, Math.min(80, newTop))}%`;

        e.preventDefault();
    }

    function stopDrag() {
        isDragging = false;
        element.classList.remove('dragging');
        document.removeEventListener('mousemove', drag);
        document.removeEventListener('touchmove', drag);
        document.removeEventListener('mouseup', stopDrag);
        document.removeEventListener('touchend', stopDrag);
    }
}

function addRandomComicEffect() {
    const effect = comicEffects[Math.floor(Math.random() * comicEffects.length)];
    spawnHypeWord(effect, true);
}

function clearAllHypeWords() {
    const words = hypeContainer.querySelectorAll('.hype-word');
    words.forEach((word, index) => {
        setTimeout(() => {
            word.classList.add('removing');
            setTimeout(() => word.remove(), 300);
        }, index * 50);
    });
}

// Handle user input
function handleHypeInput() {
    const text = hypeInput.value.trim();
    if (text) {
        spawnHypeWord(text, false);
        hypeInput.value = '';
    }
}

// ========================================
// CAPTURE SYSTEM
// ========================================
async function captureHype() {
    const ctx = captureCanvas.getContext('2d');

    // Get container dimensions
    const containerRect = cameraContainer.getBoundingClientRect();
    captureCanvas.width = containerRect.width * 2; // Higher res
    captureCanvas.height = containerRect.height * 2;

    // Scale context
    ctx.scale(2, 2);

    // Draw video (mirrored to match preview)
    ctx.save();
    ctx.translate(containerRect.width, 0);
    ctx.scale(-1, 1);

    // Apply comic filter effect manually
    ctx.filter = 'contrast(1.4) saturate(0.3) brightness(1.1)';
    ctx.drawImage(webcam, 0, 0, containerRect.width, containerRect.height);
    ctx.restore();

    // Draw halftone overlay effect
    drawHalftoneOverlay(ctx, containerRect.width, containerRect.height);

    // Draw vignette
    drawVignette(ctx, containerRect.width, containerRect.height);

    // Draw hype words
    await drawHypeWords(ctx, containerRect);

    // Convert to blob
    return new Promise((resolve) => {
        captureCanvas.toBlob((blob) => {
            currentImageBlob = blob;
            resolve(blob);
        }, 'image/png', 1.0);
    });
}

function drawHalftoneOverlay(ctx, width, height) {
    ctx.save();
    ctx.globalAlpha = 0.1;
    ctx.fillStyle = '#000';

    const dotSize = 2;
    const spacing = 4;

    for (let x = 0; x < width; x += spacing) {
        for (let y = 0; y < height; y += spacing) {
            ctx.beginPath();
            ctx.arc(x, y, dotSize / 2, 0, Math.PI * 2);
            ctx.fill();
        }
    }

    ctx.restore();
}

function drawVignette(ctx, width, height) {
    const gradient = ctx.createRadialGradient(
        width / 2, height / 2, 0,
        width / 2, height / 2, Math.max(width, height) / 1.5
    );
    gradient.addColorStop(0, 'transparent');
    gradient.addColorStop(0.5, 'transparent');
    gradient.addColorStop(1, 'rgba(0,0,0,0.6)');

    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, width, height);
}

async function drawHypeWords(ctx, containerRect) {
    const words = hypeContainer.querySelectorAll('.hype-word');

    words.forEach((word) => {
        const wordRect = word.getBoundingClientRect();
        const style = window.getComputedStyle(word);
        const textSpan = word.querySelector('.hype-text');
        const text = textSpan ? textSpan.textContent : word.textContent;

        // Calculate relative position
        const x = wordRect.left - containerRect.left + wordRect.width / 2;
        const y = wordRect.top - containerRect.top + wordRect.height / 2;

        // Get rotation
        const transform = style.transform;
        let rotation = 0;
        if (transform !== 'none') {
            const values = transform.match(/matrix\(([^)]+)\)/);
            if (values) {
                const parts = values[1].split(',').map(Number);
                rotation = Math.atan2(parts[1], parts[0]);
            }
        }

        ctx.save();
        ctx.translate(x, y);
        ctx.rotate(rotation);

        // Style the text
        ctx.font = `bold ${parseInt(style.fontSize)}px Bangers, cursive`;
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';

        // Draw shadow/stroke
        ctx.strokeStyle = '#0a0a0f';
        ctx.lineWidth = 4;
        ctx.strokeText(text, 0, 0);

        // Color based on class
        if (word.classList.contains('pow')) {
            ctx.fillStyle = '#f0f000';
        } else if (word.classList.contains('boom')) {
            ctx.fillStyle = '#00f0ff';
        } else if (word.classList.contains('zap')) {
            ctx.fillStyle = '#ff00aa';
        } else {
            ctx.fillStyle = '#ffffff';
        }

        ctx.fillText(text, 0, 0);
        ctx.restore();
    });
}

async function handleCapture() {
    // Add visual feedback
    captureBtn.disabled = true;
    captureBtn.innerHTML = '<span class="icon">⏳</span><span class="text">CAPTURING...</span>';

    // Flash effect
    const flash = document.createElement('div');
    flash.style.cssText = `
        position: fixed;
        inset: 0;
        background: white;
        z-index: 999;
        animation: flash 0.3s ease-out forwards;
    `;
    document.body.appendChild(flash);

    // Add flash animation
    const style = document.createElement('style');
    style.textContent = `
        @keyframes flash {
            0% { opacity: 0.8; }
            100% { opacity: 0; }
        }
    `;
    document.head.appendChild(style);

    setTimeout(() => flash.remove(), 300);

    try {
        // Capture the image
        const blob = await captureHype();

        // Auto download
        downloadImage(blob);

        // Clear all hype words after capture
        clearAllHypeWords();

        // Show share popup
        showSharePopup(blob);

    } catch (error) {
        console.error('Capture error:', error);
        alert('Failed to capture. Please try again!');
    }

    // Reset button
    captureBtn.disabled = false;
    captureBtn.innerHTML = '<span class="icon">📸</span><span class="text">CAPTURE MY HYPE</span>';
}

function downloadImage(blob) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'my-hype.png';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// ========================================
// SHARE POPUP SYSTEM
// ========================================
function showSharePopup(blob) {
    const url = URL.createObjectURL(blob);
    previewImage.src = url;
    sharePopup.classList.remove('hidden');
    instagramHint.classList.add('hidden');
}

function hideSharePopup() {
    sharePopup.classList.add('hidden');
    instagramHint.classList.add('hidden');
}

async function shareToWhatsApp() {
    if (navigator.share && currentImageBlob) {
        try {
            const file = new File([currentImageBlob], 'my-hype.png', { type: 'image/png' });

            await navigator.share({
                title: 'My Hype-Man Moment! 🔥',
                text: 'Check out my epic comic-book look!',
                files: [file]
            });

            console.log('Shared successfully!');
        } catch (error) {
            if (error.name !== 'AbortError') {
                // Fallback to WhatsApp web
                fallbackWhatsAppShare();
            }
        }
    } else {
        fallbackWhatsAppShare();
    }
}

function fallbackWhatsAppShare() {
    const message = encodeURIComponent(`Check out my Hype-Man look! 🔥💥 ${websiteUrl}`);
    window.open(`https://wa.me/?text=${message}`, '_blank');
}

function handleInstagramShare() {
    // Download the image
    if (currentImageBlob) {
        downloadImage(currentImageBlob);
    }

    // Show the hint
    instagramHint.classList.remove('hidden');
}

// ========================================
// WHATSAPP BRIDGE (Pre-filled message)
// ========================================
function setupWhatsAppBridge() {
    const message = encodeURIComponent(`Check out my Hype-Man look! 🔥💥 ${websiteUrl}`);
    whatsappBridge.href = `https://wa.me/?text=${message}`;
    whatsappBridge.target = '_blank';
}

// ========================================
// EVENT LISTENERS
// ========================================
function initEventListeners() {
    // Welcome popup
    if (welcomeStartBtn) {
        welcomeStartBtn.addEventListener('click', hideWelcomePopup);
    }

    // Spawn hype word
    spawnBtn.addEventListener('click', handleHypeInput);
    hypeInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            handleHypeInput();
        }
    });

    // Clear all words
    if (clearAllBtn) {
        clearAllBtn.addEventListener('click', clearAllHypeWords);
    }

    // Capture
    captureBtn.addEventListener('click', handleCapture);

    // Share popup
    closePopupBtn.addEventListener('click', hideSharePopup);
    sharePopup.addEventListener('click', (e) => {
        if (e.target === sharePopup) {
            hideSharePopup();
        }
    });

    // Share buttons
    shareWhatsappBtn.addEventListener('click', shareToWhatsApp);
    shareInstagramBtn.addEventListener('click', handleInstagramShare);

    // Keyboard shortcuts
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            hideSharePopup();
            hideWelcomePopup();
        }
        if (e.key === ' ' && document.activeElement !== hypeInput && welcomePopup.classList.contains('hidden')) {
            e.preventDefault();
            handleCapture();
        }
    });
}

// ========================================
// INITIALIZATION
// ========================================
async function init() {
    console.log('🚀 Hype-Man Studio initializing...');

    await initCamera();
    initEventListeners();
    setupWhatsAppBridge();

    // Check for first visit
    checkFirstVisit();

    console.log('✅ Hype-Man Studio ready!');
}

// Start the app
init();
